import { initStore, getDb } from "@/lib/store";
import { advanceNcr } from "@/features/quality/actions";
import { startMaintenance, waitForParts, completeMaintenanceOrder, toggleChecklistItem, createWorkRequest } from "@/features/maintenance/actions";
import { effStatus } from "@/features/maintenance/lib";
initStore();
let db = getDb();
const ncr = db.ncrs.find((n) => n.status === "open")!;
const seq = [];
for (let i = 0; i < 7; i++) seq.push(advanceNcr(ncr.id));
const after = getDb().ncrs.find((n) => n.id === ncr.id)!;
console.log("ncr flow", seq, after.status, after.closedAt);
const pm = db.maintenance.find((m) => m.status === "overdue")!;
const mBefore = db.machines.find((m) => m.id === pm.machineId)!;
console.log("pm", pm.id, effStatus(pm, db.today), "machine", mBefore.status, mBefore.lastPm, mBefore.nextPm);
toggleChecklistItem(pm.id, 0);
startMaintenance(pm.id);
db = getDb();
console.log("started", db.maintenance.find((m) => m.id === pm.id)!.status, db.machines.find((m) => m.id === pm.machineId)!.status, db.maintenance.find((m) => m.id === pm.id)!.checklist[0].done);
waitForParts(pm.id);
console.log("waiting", getDb().maintenance.find((m) => m.id === pm.id)!.status);
completeMaintenanceOrder(pm.id);
db = getDb();
const done = db.maintenance.find((m) => m.id === pm.id)!;
const mAfter = db.machines.find((m) => m.id === pm.machineId)!;
console.log("completed", done.status, done.completedDate, done.costEur, mAfter.status, mAfter.lastPm, mAfter.nextPm);
const mo = createWorkRequest({ machineId: "LSR-11", type: "calibration", title: "Calibration — test", titleTr: "Kalibrasyon — test", priority: "normal", technicianId: db.employees.find((e) => e.role === "maintenance_tech")!.id, plantId: "P1", scheduledDate: db.today, estHours: 2 });
console.log("created", mo.id, mo.status, mo.checklist.length);
completeMaintenanceOrder(mo.id);
console.log("created+completed cost", getDb().maintenance.find((m) => m.id === mo.id)!.costEur);
